settings:
  title: 'Icon Solutions Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-ayiosminasltd-com
    name: www.ayiosminasltd.com
    url: 'https://ayiosminasltd.com/'
    method: GET
    expectStatus: 200

  - id: www-caoutdoorshelters-com
    name: www.caoutdoorshelters.com
    url: 'https://caoutdoorshelters.com/'
    method: GET
    expectStatus: 200

  - id: www-demosgeorgiades-com
    name: www.demosgeorgiades.com
    url: 'https://demosgeorgiades.com/'
    method: GET
    expectStatus: 200

  - id: www-depcon-com-cy
    name: www.depcon.com.cy
    url: 'https://depcon.com.cy/'
    method: GET
    expectStatus: 200
  
  - id: www-grounded-sportswear-com
    name: www.groundedsportswear.com
    url: 'https://groundedsportswear.com/'
    method: GET
    expectStatus: 200

  - id: www.icon-cy # unique identifier
    name: www.icon.cy
    description: 'ICON SOLUTIONS CY' # default=empty
    url: 'https://www.icon.cy/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: www-instofyouth-com
    name: www.instofyouth.com
    url: 'https://instofyouth.com/'
    method: GET
    expectStatus: 200

  - id: www-leodoes-com
    name: www.leodoes.com
    url: 'https://leodoes.com/'
    method: GET
    expectStatus: 200

  - id: www-mastertype-com-cy
    name: www.mastertype.com.cy
    url: 'https://mastertype.com.cy/'
    method: GET
    expectStatus: 200

  - id: www-megaequitycasp-com
    name: www.megaequitycasp.com
    url: 'https://megaequitycasp.com/'
    method: GET
    expectStatus: 200

  - id: www-megaequity-com
    name: www.megaequity.com
    url: 'https://megaequity.com/'
    method: GET
    expectStatus: 200

  - id: www-mega-ploutos-aifm-com
    name: www.mpaifm.com
    url: 'https://mpaifm.com/'
    method: GET
    expectStatus: 200

  - id: www-mega-ploutos-com
    name: www.megaploutos.com
    url: 'https://megaploutos.com/'
    method: GET
    expectStatus: 200

  - id: www-naturelea-com
    name: www.naturelea.com
    description: 'Naturelea products'
    url: 'https://naturelea.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: www-ppkm-com-cy
    name: www.ppkm.com.cy
    url: 'https://ppkm.com.cy/'
    method: GET
    expectStatus: 200

  - id: www-thespeechbuddies-com
    name: www.thespeechbuddies.com
    url: 'https://thespeechbuddies.com/'
    method: GET
    expectStatus: 200